### ISSUE TITLE
USER STORY: Manage Polls

### ISSUE THREAD

**Issue by KC-7** [KC-7/first-agile-project#6]
In order to **manage the polls**,
as a **site administrator**,
I can **edit and delete polls**.

## Acceptance Criteria:
* The  admin can edit the polls question and options
* The admin can delete the poll
* The admin can easily create additional polls

## Tasks:
- [ ] Implement a feature to allow the admin to edit the poll
- [ ] Implement a feature to allow the admin to remove the poll
- [ ] Implement a feature to allow the admin to create a new poll
