### ISSUE TITLE
USER STORY: Alert users about poll

### ISSUE THREAD

**Issue by KC-7** [KC-7/first-agile-project#7]
In order to **increase user engagement**,
as a **site administrator**,
I can **contact our users to let them know about the poll**.

## Acceptance Criteria:
* Users can receive a push notification when a poll is created.
* Users can disable notifications. 
* Users can receive notifications by email. 
* Users can modify email preferences. 

## Tasks:
- [ ] Implement a feature to send push notifications to users
- [ ] Implement a feature to allow users to disable push notifications 
- [ ] Implement a feature to email users on the email list
- [ ] Create an option at the end of the email for users to modify email preferences
